name = "todoleet"
type = "webpack"

account_id = "19a745c88f8264f29c608584b7e417ab"
compatibility_date = "2021-12-11"
route = ""
workers_dev = false
zone_id = "e69d9e8116a9787a7c36dc16f6195ae2"

[triggers]
crons = ["1 0 * * *"]
