name: CI
on:
    push:
        branches:
            - main
    repository_dispatch:
jobs:
    build-and-deploy:
        name: Build & Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build --if-present
              env:
                  CI: true
            - name: Deploy to Cloudflare
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
