name: CI
on:
    push:
        branches:
            - main
    repository_dispatch:
jobs:
    build-and-deploy:
        name: Build & Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 'lts/*'
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build --if-present
              env:
                  CI: true
            - name: Deploy to Cloudflare
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
