name: CI
on:
    push:
        branches:
            - main
    repository_dispatch:
jobs:
    build-and-deploy:
        name: Build & Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - uses: actions/checkout@v2

            - name: Build Using Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 'lts/*'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build --if-present
              env:
                  CI: true

            - name: Deploy
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
